import re
from typing import List, Dict, Optional
from dataclasses import dataclass

@dataclass
class DetectionResult:
    is_agent: bool
    agent_name: Optional[str]
    confidence: float
    reason: str

class AgentMonitor:
    """
    Monitors code changes and commits for signs of AI Agent activity.
    """
    
    # Known patterns in commit messages or PR bodies
    COMMIT_PATTERNS = [
        (r"generated by", "Generic Generator"),
        (r"auto-generated", "Generic Generator"),
        (r"Co-authored-by:.*Copilot", "GitHub Copilot"),
        (r"Signed-off-by:.*AI", "Generic AI"),
    ]
    
    # Code patterns (comments, headers)
    CODE_PATTERNS = [
        (r"// This file was generated by", "Generic Codegen"),
        (r"# This file was generated by", "Generic Codegen"),
    ]

    def detect_from_commit_message(self, message: str) -> DetectionResult:
        for pattern, agent in self.COMMIT_PATTERNS:
            if re.search(pattern, message, re.IGNORECASE):
                return DetectionResult(
                    is_agent=True,
                    agent_name=agent,
                    confidence=0.9,
                    reason=f"Matched commit pattern: {pattern}"
                )
        return DetectionResult(False, None, 0.0, "No pattern matched")

    def detect_from_diff(self, diff_content: str) -> DetectionResult:
        """
        Analyze the diff content for patterns.
        """
        # Simple regex check on added lines
        # In a real impl, we'd parse the diff to only check added lines
        for pattern, agent in self.CODE_PATTERNS:
            if re.search(pattern, diff_content):
                 return DetectionResult(
                    is_agent=True,
                    agent_name=agent,
                    confidence=0.8,
                    reason=f"Matched code pattern: {pattern}"
                )
        return DetectionResult(False, None, 0.0, "No pattern matched")
